### ISSUE TITLE
problem using EOP

### ISSUE THREAD

**Issue by diziup** [hltfbk/Excitement-Open-Platform#523]
Hello,
I am trying to use the new version of EOP and encountering some problems using it:
1. Following the instructions here - https://github.com/hltfbk/EOP-1.2.1/wiki/Step-by-Step-Tutorial
I am using the command line CLI, in this path ~/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/
this part of the command -
eu.excitementproject.eop.util.runner.EOPRunner-
there is no matching jar for this..
2. I do not have data to train on but only pairs of T/H to annotate as entailment or not, using the AlignmentEDAP1 algorithm, 
is there a configuration file that is required for it?

Thank you,
Liora

**Comment by rzanoli** [comment]
Hello,

Here is a basic configuration file that you can use with P!EDA and English language (you need to have TreeTagger already installed). Please note that to annotate a whole data set as well as a single T/H pair you have to use either a precomputed model (when available) or you have to train the EDA on a training data set (as far as I know, with P!EDA no precomputed models are distributed and so you have to train it before annotating). In case of necessity, I think that Gil, who developed that EDA, could provide you with additional information.  

Let us know if it works.

Best,
Roberto


For training:
=========
From: ~/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1

run the following command:

java -Djava.ext.dirs=../EOP-1.2.1/ eu.excitementproject.eop.util.runner.EOPRunner
   -config /tmp/P1EDA_Base_EN.xml
   -train 
   -trainFile ./eop-resources-1.2.1/data-set/English_dev.xml


For annotating a single pair:
====================
java -Djava.ext.dirs=../EOP-1.2.1/ eu.excitementproject.eop.util.runner.EOPRunner -config /tmp/P1EDA_Base_EN.xml -test -text "Hubble is a telescope that rotates with Earth." -hypothesis "Hubble is an instrument that orbits Earth." -output /tmp/

P!EDA basic configuration file:
======================

<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE configuration>

<configuration>

        <section name="PlatformConfiguration">
                
                <property name="activatedEDA">eu.excitementproject.eop.alignmentedas.p1eda.sandbox.FNR_EN</property>
                <property name="language">EN</property>
                <property name="activatedLAP">eu.excitementproject.eop.lap.dkpro.TreeTaggerEN</property>
        </section>


        <section name="eu.excitementproject.eop.alignmentedas.p1eda.sandbox.FNR_EN">
                <property name="modelFile">/tmp//P1EDA_Base_EN.model</property>
                <property name="trainDir">/tmp/dev/</property>
                <property name="testDir">/tmp/test/</property>
        </section>

</configuration>

**Comment by diziup** [comment]
Hi ,
Thank you for the thorough response,
I do not have enough data to perform training with,
if you could please provide specific contact information of Gil, to see if
there any available model(s) for me to use,

Much thanks,
Liora

**Comment by gilnoh** [comment]
Hello Liora, 

I do not have data other than RTE training/test set (which you should already have).  --- and I do not keep any models. 

Excitement project also produced a set of "industry" data; but I am not sure which part is open (public) and which part is not. 

I suggest you close this topic, and raise the question in the EOP user mailing list: people might have some useful models for you; or at least you will get better pointers to various training data. 

Sincerely, 
Gil

**Comment by rzanoli** [comment]
You can take a look at the data sets that are distributed with the EOP at this address: https://github.com/hltfbk/EOP-1.2.1/wiki/Data-Sets

**Comment by diziup** [comment]
Hi,

I have used the command suggested by Roberto  and receive errors, which the
cause for is :
Caused by: java.io.IOException: Unable to locate model [en] in the
following locations
[classpath:/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/tagger-en-little-endian.par,
/
lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/lap/src/scripts/treetagger/lib/tagger-en-little-endian.par].
Make sure the environment variable 'TREETAGGER_HOME' or 'TAGDIR' or the
system property 'treetagger.home' point to the TreeTagger installation
directory.
 (the entire output is in the attached error.txt file).

I saw that indeed this variable was not configured,
so I configured it to the treetagger path, yet the problem persists.

Any suggestions for the problem?
Thank you,
Liora


On Tue, Mar 31, 2015 at 10:17 AM, rzanoli <notifications@github.com> wrote:

> Closed #523
> <https://github.com/hltfbk/Excitement-Open-Platform/issues/523>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/hltfbk/Excitement-Open-Platform/issues/523#event-269263741>
> .
>

liorab@ieir53 ~/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1 $ java -Djava.ext.dirs=../EOP-1.2.1/ eu.excitementproject.eop.util.runner.EOPRunner -config ./tmp/P1EDA_Base_EN.xml -train -trainFile ./eop-resources-1.2.1/data-set/English_dev.xml  > run
15/04/01 12:20:55 INFO runner.EOPRunner: running the EOP
15/04/01 12:20:55 INFO runner.EOPRunner: Configuration file: ./tmp/P1EDA_Base_EN.xml
15/04/01 12:20:55 INFO runner.EOPRunner: Initializing EDA from file /lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/./tmp/P1EDA_Base_EN.xml
15/04/01 12:20:55 INFO runner.ConfigFileUtils:getAttribute: EDA class name from config file: eu.excitementproject.eop.alignmentedas.p1eda.sandbox.FNR_EN
15/04/01 12:20:55 INFO phraselink.MeteorPhraseTable: Loading Meteor Paraphrase table from resource path: /meteor-1.5/data/paraphrase-en
15/04/01 12:21:12 INFO phraselink.MeteorPhraseTable: loading complelte, 5274084 entries. (in 16 seconds)
15/04/01 12:21:12 INFO runner.EOPRunner: EDA object created from class class eu.excitementproject.eop.alignmentedas.p1eda.sandbox.FNR_EN
15/04/01 12:21:12 INFO runner.ConfigFileUtils:getAttribute: Looking for a value for attribute: language
15/04/01 12:21:12 INFO runner.ConfigFileUtils:getAttribute: Value for attribute language : EN
15/04/01 12:21:12 INFO runner.ConfigFileUtils:getAttribute: Looking for a value for attribute: language
15/04/01 12:21:12 INFO runner.ConfigFileUtils:getAttribute: Value for attribute language : EN
15/04/01 12:21:12 INFO runner.ConfigFileUtils:getAttribute: Looking for a value for attribute: activatedLAP
15/04/01 12:21:12 INFO runner.ConfigFileUtils:getAttribute: Value for attribute activatedLAP : eu.excitementproject.eop.lap.dkpro.TreeTaggerEN
15/04/01 12:21:12 INFO runner.LAPRunner: LAP initialized from class eu.excitementproject.eop.lap.dkpro.TreeTaggerEN
15/04/01 12:21:13 INFO runner.ConfigFileUtils:getAttribute: Looking for a value for attribute: trainDir
15/04/01 12:21:13 INFO runner.ConfigFileUtils:getAttribute: Value for attribute trainDir : /lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/tmp/dev/
15/04/01 12:21:13 INFO runner.EOPRunner:         training file: ./eop-resources-1.2.1/data-set/English_dev.xml
         training dir: /lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/tmp/dev/
15/04/01 12:21:13 INFO runner.LAPRunner: Running lap on file: ./eop-resources-1.2.1/data-set/English_dev.xml // writing output to directory /lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/tmp/dev/
15/04/01 12:21:14 INFO opennlp.OpenNlpSegmenter$1: Producing resource from jar:file:/lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/de.tudarmstadt.ukp.dkpro.core.opennlp-model-sentence-en-maxent-20120616.0.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/sentence-en-maxent.bin
15/04/01 12:21:14 INFO opennlp.OpenNlpSegmenter$2: Producing resource from jar:file:/lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/de.tudarmstadt.ukp.dkpro.core.opennlp-model-token-en-maxent-20120616.0.jar!/de/tudarmstadt/ukp/dkpro/core/opennlp/lib/token-en-maxent.bin
Apr 01, 2015 12:21:14 PM org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentProcess(407)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:206)
        at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:375)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:296)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:567)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBaseAE.addAnnotationOn(LAP_ImplBaseAE.java:167)
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBase.processRawInputFormat(LAP_ImplBase.java:142)
        at eu.excitementproject.eop.util.runner.LAPRunner.runLAPOnFile(LAPRunner.java:205)
        at eu.excitementproject.eop.util.runner.EOPRunner.run(EOPRunner.java:414)
        at eu.excitementproject.eop.util.runner.EOPRunner.main(EOPRunner.java:463)
Caused by: java.io.IOException: Unable to locate model [en] in the following locations [classpath:/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/tagger-en-little-endian.par, /
lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/lap/src/scripts/treetagger/lib/tagger-en-little-endian.par].  Make sure the environment variable 'TREETAGGER_HOME' or 'TAGDIR' or the system property 'treetagger.home' point to the TreeTagger installation directory.
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerTT4JBase$DKProModelResolver.getModel(TreeTaggerTT4JBase.java:378)
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerTT4JBase$DKProModelResolver.getModel(TreeTaggerTT4JBase.java:290)
        at org.annolab.tt4j.TreeTaggerWrapper.setModel(TreeTaggerWrapper.java:471)
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:148)
        ... 14 more

Apr 01, 2015 12:21:14 PM org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl processAndOutputNewCASes(275)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:206)
        at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:375)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:296)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:567)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBaseAE.addAnnotationOn(LAP_ImplBaseAE.java:167)
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBase.processRawInputFormat(LAP_ImplBase.java:142)
        at eu.excitementproject.eop.util.runner.LAPRunner.runLAPOnFile(LAPRunner.java:205)
        at eu.excitementproject.eop.util.runner.EOPRunner.run(EOPRunner.java:414)
        at eu.excitementproject.eop.util.runner.EOPRunner.main(EOPRunner.java:463)
Caused by: java.io.IOException: Unable to locate model [en] in the following locations [classpath:/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/tagger-en-little-endian.par, /
lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/lap/src/scripts/treetagger/lib/tagger-en-little-endian.par].  Make sure the environment variable 'TREETAGGER_HOME' or 'TAGDIR' or the system property 'treetagger.home' point to the TreeTagger installation directory.
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerTT4JBase$DKProModelResolver.getModel(TreeTaggerTT4JBase.java:378)
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerTT4JBase$DKProModelResolver.getModel(TreeTaggerTT4JBase.java:290)
        at org.annolab.tt4j.TreeTaggerWrapper.setModel(TreeTaggerWrapper.java:471)
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:148)
        ... 14 more

Error running the LAP
eu.excitementproject.eop.lap.LAPException: Underlying AE or AAE reported an exception
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBaseAE.addAnnotationOn(LAP_ImplBaseAE.java:171)
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBase.processRawInputFormat(LAP_ImplBase.java:142)
        at eu.excitementproject.eop.util.runner.LAPRunner.runLAPOnFile(LAPRunner.java:205)
        at eu.excitementproject.eop.util.runner.EOPRunner.run(EOPRunner.java:414)
        at eu.excitementproject.eop.util.runner.EOPRunner.main(EOPRunner.java:463)
Caused by: org.apache.uima.analysis_engine.AnalysisEngineProcessException
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:206)
        at org.apache.uima.analysis_component.CasAnnotator_ImplBase.process(CasAnnotator_ImplBase.java:56)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:375)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:296)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:567)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:409)
        at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:342)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:267)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267)
        at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:280)
        at eu.excitementproject.eop.lap.implbase.LAP_ImplBaseAE.addAnnotationOn(LAP_ImplBaseAE.java:167)
        ... 4 more
Caused by: java.io.IOException: Unable to locate model [en] in the following locations [classpath:/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/tagger-en-little-endian.par, /
lv_local/home/liorab/EOP/Excitement-Open-Platform-1.2.1/lap/src/scripts/treetagger/lib/tagger-en-little-endian.par].  Make sure the environment variable 'TREETAGGER_HOME' or 'TAGDIR' or the system property 'treetagger.home' point to the TreeTagger installation directory.
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerTT4JBase$DKProModelResolver.getModel(TreeTaggerTT4JBase.java:378)
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerTT4JBase$DKProModelResolver.getModel(TreeTaggerTT4JBase.java:290)
        at org.annolab.tt4j.TreeTaggerWrapper.setModel(TreeTaggerWrapper.java:471)
        at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:148)
        ... 14 more

**Comment by rzanoli** [comment]
Here the issue appears to be related to the TreeTagger installation. Have you installed it when you installed the EOP (e.g., install.sh 1.2.1 treetagger) or you installed it by yourself?

**Comment by diziup** [comment]
Using  ./install.sh 1.2.1 treetagger:

**Comment by rzanoli** [comment]
I would need the content of this directory: lap/src/target/model-staging/de/tudarmstadt/ukp/dkpro/core/treetagger/lib/

**Comment by diziup** [comment]
Are you referring to this path -  ../Excitement-Open-Platform-1.2.1/lap/src?
Because if so, then there is no target dir in it, but only main, script,
and test directories

**Comment by rzanoli** [comment]
That directory should contain some files and tagger-en-little-endian.par too. Then the install.sh script should have also produced the following jar Excitement-Open-Platform-1.2.1/target/EOP-1.2.1/de.tudarmstadt.ukp.dkpro.core.treetagger-model-en-20111109.0.jar containing the same tagger-en-little-endian.par file.

If you don't have this file it means that the install script didn't work correctly but as far as I know, in that case,  it should have produced an error. Would you repeat the installation procedure? Download the install.sh script from its web site as well as the build.xml and rerun the script.

**Comment by diziup** [comment]
You are right,
re-installing solved the issue,
thank you very much for the quick help,

Liora
