### ISSUE TITLE
Build failure on the core package

### ISSUE THREAD

**Issue by HyperColumn** [hltfbk/Excitement-Open-Platform#553]
I'm using ubuntu 16.04.3, openjdk version "9-internal" 
The build fails on the core package with the following output:

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.IllegalAccessError: class lombok.javac.apt.Processor (in unnamed module @0x3c1a3112) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x3c1a3112
	at lombok.javac.apt.Processor.init(Processor.java:84)
	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(jdk.compiler@9-internal/JavacProcessingEnvironment.java:671)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(jdk.compiler@9-internal/JavacProcessingEnvironment.java:768)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(jdk.compiler@9-internal/JavacProcessingEnvironment.java:859)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(jdk.compiler@9-internal/JavacProcessingEnvironment.java:106)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(jdk.compiler@9-internal/JavacProcessingEnvironment.java:1181)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(jdk.compiler@9-internal/JavacProcessingEnvironment.java:1289)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(jdk.compiler@9-internal/JavaCompiler.java:1229)
	at com.sun.tools.javac.main.JavaCompiler.compile(jdk.compiler@9-internal/JavaCompiler.java:903)
	at com.sun.tools.javac.main.Main.compile(jdk.compiler@9-internal/Main.java:261)
	at com.sun.tools.javac.main.Main.compile(jdk.compiler@9-internal/Main.java:143)
	at com.sun.tools.javac.Main.compile(jdk.compiler@9-internal/Main.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:551)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:526)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:167)
	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:678)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Free Open Source Platform for Recognizing Textual Entailments (RTE) SUCCESS [  0.228 s]
[INFO] common ............................................. SUCCESS [ 12.070 s]
[INFO] redis .............................................. SUCCESS [  0.038 s]
[INFO] lap ................................................ SUCCESS [ 28.536 s]
[INFO] distsim ............................................ SUCCESS [  0.592 s]
[INFO] lexicalminer ....................................... SUCCESS [  0.084 s]
[INFO] core ............................................... FAILURE [  2.392 s]
[INFO] transformations .................................... SKIPPED
[INFO] biutee ............................................. SKIPPED
[INFO] alignmentedas ...................................... SKIPPED
[INFO] adarte ............................................. SKIPPED
[INFO] util ............................................... SKIPPED
[INFO] globalgraphoptimizer ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.146 s
[INFO] Finished at: 2018-01-03T12:54:04+02:00
[INFO] Final Memory: 53M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project core: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] Note: Some input files use or override a deprecated API.
[ERROR] Note: Recompile with -Xlint:deprecation for details.
[ERROR] 
[ERROR] 
[ERROR] An annotation processor threw an uncaught exception.
[ERROR] Consult the following stack trace for details.
[ERROR] java.lang.IllegalAccessError: class lombok.javac.apt.Processor (in unnamed module @0x3c1a3112) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x3c1a3112
[ERROR] at lombok.javac.apt.Processor.init(Processor.java:84)
[ERROR] at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
[ERROR] at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:141)
[ERROR] at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:53)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(jdk.compiler@9-internal/JavacProcessingEnvironment.java:671)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(jdk.compiler@9-internal/JavacProcessingEnvironment.java:768)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(jdk.compiler@9-internal/JavacProcessingEnvironment.java:859)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(jdk.compiler@9-internal/JavacProcessingEnvironment.java:106)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(jdk.compiler@9-internal/JavacProcessingEnvironment.java:1181)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(jdk.compiler@9-internal/JavacProcessingEnvironment.java:1289)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.processAnnotations(jdk.compiler@9-internal/JavaCompiler.java:1229)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.compile(jdk.compiler@9-internal/JavaCompiler.java:903)
[ERROR] at com.sun.tools.javac.main.Main.compile(jdk.compiler@9-internal/Main.java:261)
[ERROR] at com.sun.tools.javac.main.Main.compile(jdk.compiler@9-internal/Main.java:143)
[ERROR] at com.sun.tools.javac.Main.compile(jdk.compiler@9-internal/Main.java:73)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:551)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:526)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:167)
[ERROR] at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:678)
[ERROR] at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

let me know if you can help

**Comment by HyperColumn** [comment]
Here's a recipe that worked good for me:
https://github.com/airdock-io/docker-oracle-jdk/tree/master/jdk-1.7 as a docker os + maven 3.0.5 from tarball + ant from apt-get
